---
dmvpn_role: spoke
dmvpn_tunnel_ip: 172.30.0.8
dmvpn_source_ip: 10.5.8.2
ospf_router_id: 8.8.8.8

# Routes statiques côté client 2
static_routes:
  # Réseaux services via le hub
  - network: 192.168.10.0
    mask: 255.255.255.0
    next_hop: 172.30.0.1
  - network: 192.168.20.0
    mask: 255.255.255.0
    next_hop: 172.30.0.1

  # Client 1 via DMVPN
  - network: 192.168.2.0
    mask: 255.255.255.0
    next_hop: 172.30.0.7

ospf_networks:
  - "172.30.0.0 0.0.0.255 area 0"
  - "192.168.3.0 0.0.0.255 area 0"
