#Partie Infra réseaux

# inventory.ini

[routers]
IOU1 ansible_host=172.16.0.11
IOU2 ansible_host=172.16.0.12
IOU3 ansible_host=172.16.0.13
IOU4 ansible_host=172.16.0.14
IOU5 ansible_host=172.16.0.15
IOU6 ansible_host=172.16.0.16
IOU7 ansible_host=172.16.0.17
IOU8 ansible_host=172.16.0.18

[switches]
IOU9 ansible_host=172.16.0.19
Switch1 ansible_host=172.16.0.1
Switch2 ansible_host=172.16.0.2
Switch3 ansible_host=172.16.0.3

[services]
VMServices ansible_host=172.16.0.4

[routers:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin123
ansible_network_cli_ssh_type=paramiko
ansible_host_key_checking=False

[switches:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin123

[services:vars]
ansible_connection=ssh
ansible_user=services
ansible_password=lmc
ansible_become=yes
ansible_become_method=su
ansible_become_user=root
ansible_become_password=lmc
ansible_remote_tmp=/tmp/.ansible-${USER}/tmp

[dmvpn_hub]
IOU1

[dmvpn_spokes]
IOU7
IOU8

[dmvpn:children]
dmvpn_hub
dmvpn_spokes

[dmvpn:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin123
ansible_network_cli_ssh_type=paramiko
ansible_host_key_checking=False
