version: '3'

services:
  mail:
    image: mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: saecoef61.local

    ports:
      - "25:25"
      - "143:143"

    restart: unless-stopped

    volumes:
      - ./data:/var/mail
      - ./state:/var/mail-state
      - ./logs:/var/log/mail
      - ./config:/tmp/docker-mailserver

    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0

